### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by cabb** [IzumiSy/sinatra-validation#17]
Do you plan to perform the release of 0.4.0?
It would be great to use this gem with the newest sinatra version.

Thanks for you work so far!

**Comment by cabb** [comment]
ping

**Comment by IzumiSy** [comment]
Sorry to be late for replying. I will work on releasing 0.4.0 in my spare time, so please use this by referencing `master` branch for now.

**Comment by cabb** [comment]
ping

**Comment by cabb** [comment]
ping

**Comment by cabb** [comment]
It would still be very cool to have a next release

**Comment by IzumiSy** [comment]
@cabb 
Really sorry for this issue. Can you open a PR to release 0.4.0?

**Comment by cabb** [comment]
I created a PR containing updates to ruby and sinatra. #18 
Thanks for your project

**Comment by cabb** [comment]
Everything seems to be merged. Only a release to rubygems is missing. 
When I can assist you, let me know.

**Comment by IzumiSy** [comment]
@cabb 
Really, really sorry to make you wait for years, but thank you a lot and finally published 0.4.0. Check that out.

https://rubygems.org/gems/sinatra-validation/versions/0.4.0

**Comment by IzumiSy** [comment]
Reopen this issue again if something is missed. Closing by 0.4.0 release.
