### ISSUE TITLE
Issue with dry-validation 1.3

### ISSUE THREAD

**Issue by bsesso** [IzumiSy/sinatra-validation#7]
I was trying to use this gem, but although it seems to automatically install the latest dry-validation  gem, it doesn't support it.
I kept having the following error until I downgrade the version of dry-validation to 0.13.

> Undefined method `Schema' for Dry::Validation:Module

Issue related to:
[https://github.com/dry-rb/dry-validation/issues/544](https://github.com/dry-rb/dry-validation/issues/544)
It seems like they have changed the syntax from 0.13 to 1.0

**Comment by IzumiSy** [comment]
Thank you @bsesso for reporting the bug. I will work on it asap.

**Comment by IzumiSy** [comment]
Please open this again if your problem still has not fixed yet.

**Comment by IzumiSy** [comment]
@bsesso I updated dry-validation to 1.3 internally. Please open this again if your problem still has not fixed yet.
